# Generated by Django 4.0.2 on 2022-02-08 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='URLshortener',
            new_name='Url',
        ),
    ]
