# Generated by Django 4.0.2 on 2022-02-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0002_rename_urlshortener_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='shortened',
            field=models.CharField(default='defaultshortenedurl', max_length=15),
            preserve_default=False,
        ),
    ]
