# Generated by Django 4.0.2 on 2022-02-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0005_url_last_updated_url_timestamp_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='active_urls',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='shortened',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
