# Generated by Django 4.0.2 on 2022-02-11 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0006_url_active_urls_alter_url_shortened'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='active_urls',
            new_name='active',
        ),
    ]
